gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ah, Bidoof is such a majestic\n"
	.string "beast. Some consider it a god.\p"
	.string "Anyway, this world is widely\n"
	.string "inhabited by many other Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "This adventure will be different\n"
	.string "than others you've had before.\p"
	.string "In fact, this has been crafted\n"
	.string "specially for RyanRossLIVE to\l"
	.string "celebrate his sixth stream\l"
	.string "anniversary.\p"
	.string "It will be filled with familiar\n"
	.string "friends, fan-favorite references,\l"
	.string "and hopefully a lot of fun.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's get started.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's joining\n"
	.string "the communitity in the Guild Lands.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Have fun!\n"
	.string "$"
