Common_EventScript_SetGymTrainers::
	switch VAR_0x8008
	case 1, RustboroCity_Gym_SetGymTrainers
	case 2, DewfordTown_Gym_SetGymTrainers
	case 3, MauvilleCity_Gym_SetGymTrainers
	case 4, LavaridgeTown_Gym_SetGymTrainers
	case 5, PetalburgCity_Gym_SetGymTrainers
	case 6, FortreeCity_Gym_SetGymTrainers
	case 7, MossdeepCity_Gym_SetGymTrainers
	case 8, SootopolisCity_Gym_SetGymTrainers
	case 9, CastleTownBlindJim_Gym_SetGymTrainers
	case 10, CastleTownAndy_Gym_SetGymTrainers
	case 11, CastleTownHermes_Gym_SetGymTrainers
	case 12, CastleTownSabre_Gym_SetGymTrainers
	case 13, CastleTownSalsa_Gym_SetGymTrainers
	case 14, CastleTownTMoney_Gym_SetGymTrainers
	case 15, CastleTownTot_Gym_SetGymTrainers
	case 16, CastleTownTreble_Gym_SetGymTrainers
	end

RustboroCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_JOSH
	settrainerflag TRAINER_TOMMY
	settrainerflag TRAINER_MARC
	return

DewfordTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_TAKAO
	settrainerflag TRAINER_JOCELYN
	settrainerflag TRAINER_LAURA
	settrainerflag TRAINER_BRENDEN
	settrainerflag TRAINER_CRISTIAN
	settrainerflag TRAINER_LILITH
	return

MauvilleCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_KIRK
	settrainerflag TRAINER_SHAWN
	settrainerflag TRAINER_JEN
	settrainerflag TRAINER_VIVIAN
	settrainerflag TRAINER_ANGEL
	return

LavaridgeTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_COLE
	settrainerflag TRAINER_AXLE
	settrainerflag TRAINER_KEEGAN
	settrainerflag TRAINER_GERALD
	settrainerflag TRAINER_DANIELLE
	settrainerflag TRAINER_JACE
	settrainerflag TRAINER_JEFF
	settrainerflag TRAINER_ELI
	return

PetalburgCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_RANDALL
	settrainerflag TRAINER_PARKER
	settrainerflag TRAINER_GEORGE
	settrainerflag TRAINER_BERKE
	settrainerflag TRAINER_MARY
	settrainerflag TRAINER_ALEXIA
	settrainerflag TRAINER_JODY
	return

FortreeCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_JARED
	settrainerflag TRAINER_FLINT
	settrainerflag TRAINER_ASHLEY
	settrainerflag TRAINER_EDWARDO
	settrainerflag TRAINER_HUMBERTO
	settrainerflag TRAINER_DARIUS
	return

MossdeepCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_PRESTON
	settrainerflag TRAINER_VIRGIL
	settrainerflag TRAINER_BLAKE
	settrainerflag TRAINER_HANNAH
	settrainerflag TRAINER_SAMANTHA
	settrainerflag TRAINER_MAURA
	settrainerflag TRAINER_SYLVIA
	settrainerflag TRAINER_NATE
	settrainerflag TRAINER_KATHLEEN
	settrainerflag TRAINER_CLIFFORD
	settrainerflag TRAINER_MACEY
	settrainerflag TRAINER_NADIA
	return

SootopolisCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_ELLIOTT
	settrainerflag TRAINER_CRISSY
	settrainerflag TRAINER_BRIANNA
	settrainerflag TRAINER_JEANETTE
	settrainerflag TRAINER_BRIDGET
	settrainerflag TRAINER_STEVE
	settrainerflag TRAINER_TIFFANY
	settrainerflag TRAINER_BETHANY
	settrainerflag TRAINER_MANFRED
	settrainerflag TRAINER_DAPHNE
	return

CastleTownBlindJim_Gym_SetGymTrainers::
	settrainerflag TRAINER_TAKAO
	settrainerflag TRAINER_JOCELYN
	settrainerflag TRAINER_LAURA
	settrainerflag TRAINER_BRENDEN
	settrainerflag TRAINER_CRISTIAN
	settrainerflag TRAINER_LILITH
	settrainerflag TRAINER_ELI
	return

CastleTownAndy_Gym_SetGymTrainers::
	settrainerflag TRAINER_TOMMY
	settrainerflag TRAINER_MARC
	settrainerflag TRAINER_MACEY
	settrainerflag TRAINER_CLIFFORD
	settrainerflag TRAINER_KATHLEEN
	settrainerflag TRAINER_SYLVIA
	settrainerflag TRAINER_JOSH
	settrainerflag TRAINER_LEAH
	return

CastleTownHermes_Gym_SetGymTrainers::
	settrainerflag TRAINER_ALEXIA
	settrainerflag TRAINER_PARKER
	settrainerflag TRAINER_MARY
	settrainerflag TRAINER_RANDALL
	settrainerflag TRAINER_JODY
	settrainerflag TRAINER_GEORGE
	settrainerflag TRAINER_BERKE
	return

CastleTownSabre_Gym_SetGymTrainers::
	settrainerflag TRAINER_ELLIOTT
	settrainerflag TRAINER_CHARLOTTE
	settrainerflag TRAINER_JEANETTE
	settrainerflag TRAINER_BRIDGET
	settrainerflag TRAINER_STEVE
	settrainerflag TRAINER_MANFRED
	settrainerflag TRAINER_DAPHNE
	return

CastleTownSalsa_Gym_SetGymTrainers::
	settrainerflag TRAINER_JACE
	settrainerflag TRAINER_AXLE
	settrainerflag TRAINER_GERALD
	settrainerflag TRAINER_KEEGAN
	settrainerflag TRAINER_DANIELLE
	settrainerflag TRAINER_JEFF
	settrainerflag TRAINER_COLE
	return

CastleTownTMoney_Gym_SetGymTrainers::
	settrainerflag TRAINER_JARED
	settrainerflag TRAINER_CRISSY
	settrainerflag TRAINER_HUMBERTO
	settrainerflag TRAINER_FLINT
	settrainerflag TRAINER_DARIUS
	settrainerflag TRAINER_EDWARDO
	settrainerflag TRAINER_ASHLEY
	return

CastleTownTot_Gym_SetGymTrainers::
	settrainerflag TRAINER_PRESTON
	settrainerflag TRAINER_VIRGIL
	settrainerflag TRAINER_BLAKE
	settrainerflag TRAINER_HANNAH
	settrainerflag TRAINER_SAMANTHA
	settrainerflag TRAINER_MAURA
	settrainerflag TRAINER_NATE
	return

CastleTownTreble_Gym_SetGymTrainers::
	settrainerflag TRAINER_ANGEL
	settrainerflag TRAINER_JEN
	settrainerflag TRAINER_BETHANY
	settrainerflag TRAINER_NADIA
	settrainerflag TRAINER_KIRK
	settrainerflag TRAINER_SHAWN
	settrainerflag TRAINER_VIVIAN
	return
